In [12]:
import pandas as pd
import numpy as np

In [13]:
file = pd.read_csv("Resources/TA_Data_V.2.csv")
ta_df = pd.DataFrame(file)
ta_df

,Date,TA.LAB.NC4.VOLPCT,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F
0,7/15/2022 13:00,11.20,10731.7002,99.30152893,134.6903534,133.1420898,1.432772994,100.6223145,5919.916992,6399.555664,97.03623199,160.8286591,177.0243378,0.66986084,98.63166809,74.77849579,315.3513489,188.9165344
1,7/15/2022 6:00,13.90,10332.8252,99.47181702,134.7993469,133.2794189,3.479724407,99.48440552,5935.238281,6395.504883,93.11539459,159.8332214,175.662384,0.578268826,98.89743805,72.92869568,312.3144531,188.0589294
2,7/14/2022 13:00,13.60,9904.880859,98.97205353,134.3727112,132.7810669,2.860878468,99.41940308,5968.467773,5933.965332,97.99095917,161.156311,178.83255,0.781860352,98.19156647,73.68263245,318.3023071,191.8672333
3,7/14/2022 6:00,11.00,9641.806641,99.94731903,134.9676514,133.2887726,4.899298191,99.85849762,6020.976074,5902.112793,92.6629715,159.7163849,176.0884705,0.605773926,99.33746338,74.87386322,312.1195374,187.9542999
4,7/13/2022 13:00,10.70,9876.027344,99.60662842,135.2410889,133.3068848,1.202635884,100.4339676,5917.750488,5749.19873,98.54929352,163.9949493,182.7541046,0.64453125,98.95614624,76.2322998,318.6087952,195.6160431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15584,1/6/2013 6:00,18.00,25122.4668,92.15240479,127.7038574,120.5078125,8.922232628,94.46717072,8196.665039,8761.213867,77.02178955,166.5435791,186.9384766,8.200836182,100.4653931,102.2613602,312.4145508,246.0876617
15585,1/5/2013 13:00,14.40,25195.29688,101.4450073,133.2214355,126.8371582,-6.900000095,103.8177567,8516.427734,9015.898438,89.14337158,173.0133057,187.1032867,8.182525635,109.6252441,101.4251785,314.0686035,233.2580719
15586,1/5/2013 6:00,10.20,24632.41406,94.03382111,128.2073975,121.8322754,-6.900000095,96.34552002,8513.540039,8986.914063,86.09161377,167.7795563,187.5335693,8.205413818,102.2163391,102.1118164,312.4023438,242.4316406
15587,1/4/2013 13:00,6.10,24166.07813,95.30639648,127.6672363,122.3083496,-6.900000095,97.55249023,8439.272461,8972.183594,85.45074463,163.192749,187.1246338,8.134460449,103.5346985,102.3620605,312.9394531,247.5585938
15588,1/4/2013 6:00,4.90,19465.98828,102.9853821,131.0302734,126.4404297,-6.900000095,105.2337723,8512.09668,9469.200195,85.30426025,162.399292,188.2049561,8.317565918,111.2319946,101.9714355,312.2619629,228.1982422

In [17]:
pd.to_datetime(ta_df['Date'])

0       2022-07-15 13:00:00
1       2022-07-15 06:00:00
2       2022-07-14 13:00:00
3       2022-07-14 06:00:00
4       2022-07-13 13:00:00
                ...
15584   2013-01-06 06:00:00
15585   2013-01-05 13:00:00
15586   2013-01-05 06:00:00
15587   2013-01-04 13:00:00
15588   2013-01-04 06:00:00
Name: Date, Length: 15589, dtype: datetime64[ns]

In [18]:
dates = ta_df['Date']
dates.to_csv(dates.csv)

<bound method Series.unique of 0        7/15/2022 13:00
1         7/15/2022 6:00
2        7/14/2022 13:00
3         7/14/2022 6:00
4        7/13/2022 13:00
              ...
15584      1/6/2013 6:00
15585     1/5/2013 13:00
15586      1/5/2013 6:00
15587     1/4/2013 13:00
15588      1/4/2013 6:00
Name: Date, Length: 15589, dtype: object>

In [4]:
names_columns = ['TA.LAB.NC4.VOLPCT',
         'TA.Charge.BPD',
      'TA.OH.PSIG',
      'TA.Tray4.F',
      'TA.OH.F',
      'TA.RECV.PCT',
      'TA.RECV.PSIG',
      'TA.REFLUX.BPD',
      'TA.RECYCLE.TO.CONTACT.BPD',
      'TA.RECYCLE.TO.CONTACT.F',
      'TA.TRAY39.F',
      'TA.TRAY45.F',
      'TA.DP.PSIG',
      'TA.BTM.PSIG',
      'TA.BTM.LEVEL.PCT',
      'TA.BTM.REBOIL.OUT.F',
      'TA.TOP.REBOIL.OUT.F']

In [5]:
for name in names_columns:
    ta_df.loc[ta_df[name] == "I/O Timeout"] = np.nan
    ta_df.loc[ta_df[name] == "Error"] = np.nan
    ta_df.loc[ta_df[name] == "Bad"] = np.nan
    ta_df.loc[ta_df[name] == "Bad Input"] = np.nan

# check to see if these have been replaced properly, should equal 1056 
ta_df.isnull().sum()

Date                         1056
TA.LAB.NC4.VOLPCT            1056
TA.Charge.BPD                1056
TA.OH.PSIG                   1056
TA.Tray4.F                   1056
TA.OH.F                      1056
TA.RECV.PCT                  1056
TA.RECV.PSIG                 1056
TA.REFLUX.BPD                1056
TA.RECYCLE.TO.CONTACT.BPD    1056
TA.RECYCLE.TO.CONTACT.F      1056
TA.TRAY39.F                  1056
TA.TRAY45.F                  1056
TA.DP.PSIG                   1056
TA.BTM.PSIG                  1056
TA.BTM.LEVEL.PCT             1056
TA.BTM.REBOIL.OUT.F          1056
TA.TOP.REBOIL.OUT.F          1056
dtype: int64

In [6]:
ta_df = ta_df.drop(columns=['Date'])
ta_df.head(1)

,TA.LAB.NC4.VOLPCT,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F
0,11.20,10731.7002,99.30152893,134.6903534,133.1420898,1.432772994,100.6223145,5919.916992,6399.555664,97.03623199,160.8286591,177.0243378,0.66986084,98.63166809,74.77849579,315.3513489,188.9165344

In [7]:
ta_df = ta_df.astype(dict.fromkeys(ta_df.columns[0:17], float))

In [8]:
ta_df.dtypes

TA.LAB.NC4.VOLPCT            float64
TA.Charge.BPD                float64
TA.OH.PSIG                   float64
TA.Tray4.F                   float64
TA.OH.F                      float64
TA.RECV.PCT                  float64
TA.RECV.PSIG                 float64
TA.REFLUX.BPD                float64
TA.RECYCLE.TO.CONTACT.BPD    float64
TA.RECYCLE.TO.CONTACT.F      float64
TA.TRAY39.F                  float64
TA.TRAY45.F                  float64
TA.DP.PSIG                   float64
TA.BTM.PSIG                  float64
TA.BTM.LEVEL.PCT             float64
TA.BTM.REBOIL.OUT.F          float64
TA.TOP.REBOIL.OUT.F          float64
dtype: object

In [9]:
#ta_df.to_csv("Resources/___")

# Run some tests on this

In [10]:
ta_df.describe()

,TA.LAB.NC4.VOLPCT,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F
count,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000,14533.000000
mean,11.245712,13621.310443,97.374001,134.740254,132.641258,16.266632,100.040837,6344.172272,6368.351702,80.869616,165.309795,178.649792,6.507864,101.950305,80.822571,316.161941,219.691596
std,9.006644,3297.796143,3.722133,2.231042,2.468915,7.724779,2.638609,974.304626,972.422257,6.882295,5.808537,10.537343,8.623358,9.806623,11.854316,8.557215,14.423369
min,0.000000,0.000000,-1.532560,96.229553,96.133430,-6.900000,54.655460,-836.645019,0.000000,27.513123,124.955238,133.705429,0.002177,3.174019,0.000000,185.351562,150.372314
25%,9.600000,12403.442380,97.009277,134.268189,132.287598,12.685467,99.757858,5846.508789,6261.166016,76.664734,162.753296,175.271606,5.117798,102.086372,74.824524,316.351318,214.831543
50%,11.100000,13263.351560,97.288513,134.878540,133.090210,17.863728,99.997444,6132.438965,6368.778320,80.793762,165.567017,177.938843,5.188751,102.458954,75.274658,318.194580,220.550552
75%,12.600000,14132.339840,97.608093,135.479736,133.496094,21.001371,100.241096,6804.629395,6486.984863,85.063171,168.045044,179.959106,5.451954,102.973602,83.819580,320.172119,225.720215
max,1005.000000,29901.033200,133.076477,194.899170,194.660858,105.000000,136.087036,12522.957030,16473.312500,113.681038,299.072266,331.774933,101.661385,141.533661,199.996948,359.384460,329.602081

In [11]:
ta_df.loc[ta_df['TA.LAB.NC4.VOLPCT'] == 0]

,TA.LAB.NC4.VOLPCT,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F
447,0.0,11500.64551,99.347221,134.806625,133.015243,5.544438,99.786819,7551.181152,6509.578613,82.996468,167.459686,185.528305,0.150270,99.227394,89.129494,305.673614,204.364105
1576,0.0,14379.28711,97.114563,135.656738,133.764648,12.399405,100.091553,6584.439941,6245.961426,86.827087,166.055298,174.270630,5.126953,102.261597,85.421761,302.392578,194.738769
1588,0.0,13935.48047,97.262321,134.718414,133.240250,12.055746,99.987244,3009.101074,6314.649414,87.093399,163.800903,173.681641,5.118179,102.368103,84.925926,311.520569,189.682266
1659,0.0,13259.45996,97.055061,138.708496,136.239624,12.204254,99.888611,2764.456055,9249.439453,89.820862,171.731567,180.862427,4.872894,101.957703,86.293030,308.886719,207.049576
1698,0.0,14037.86719,97.375877,139.358520,136.991623,21.232347,100.087090,6678.454102,6555.257324,83.176292,171.533569,180.884689,4.899020,102.237221,85.330200,307.733459,205.299499
1727,0.0,12977.01172,97.099632,133.711472,131.090302,11.400844,99.966866,3597.633301,6199.368652,89.172363,161.207367,175.868744,4.925207,102.043480,79.385803,325.598144,232.740433
12423,0.0,11119.15625,97.732552,131.707764,127.917480,8.711593,100.524902,6398.873535,6412.147461,83.992004,166.384888,178.955078,8.493805,106.192024,74.887085,321.289062,213.739029
13225,0.0,19207.41211,97.572327,133.496094,131.802368,9.465595,100.137337,7631.200195,6438.281250,84.272766,160.913086,174.380493,8.674622,106.276703,75.440979,321.032715,203.607193
13521,0.0,14265.96875,97.135162,136.874390,133.175659,11.553231,100.073242,6812.193848,5980.109863,90.853889,174.008179,183.160416,7.621758,104.759216,69.837952,299.664307,225.885025
14734,0.0,14857.64355,113.404083,140.722656,136.013794,-6.900000,116.384895,6546.377441,6487.460449,98.561096,167.129517,174.838257,7.461555,120.904541,101.705940,292.321777,216.473404
15476,0.0,26523.17773,92.612457,130.880737,129.095459,10.187135,94.758606,8507.144531,9357.299805,77.474976,163.217163,177.774048,8.386230,101.010139,103.024300,299.652100,205.194107

# Note
December 2018 to march 29th, 2019 data is off, need to check
Turnaround for the plant, things were shut down during this time, so these values need to be removed