In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from connection import get_db_connection

# establish connect with postgres database to extract data
conn = get_db_connection()
cursor = conn.cursor()
cursor.execute("select * from lab_tc")
result = cursor.fetchall()

df = pd.DataFrame(result)

column_names = ['Date', 
	'N_Butane',
    'TC_Tray7_Temp',
	'TC_Tray40_Temp',
	'TC_Charge_Temp',
	'TC_Overhead_Pressure',
	'TC_Overhead_Reciever_Temp',
	'TC_Tray24_Temp',
	'TC_Differential_Pressure',
	'TC_Bottom_Pressure',
	'TC_Reboil_Out_Temp',
	"TC_Reboil_Condensor_lbs"
]

df.columns = column_names
df.head()

3953
Hello

,Date,N_Butane,TC_Tray7_Temp,TC_Tray40_Temp,TC_Charge_Temp,TC_Overhead_Pressure,TC_Overhead_Reciever_Temp,TC_Tray24_Temp,TC_Differential_Pressure,TC_Bottom_Pressure,TC_Reboil_Out_Temp,TC_Reboil_Condensor_lbs
0,2022-07-15 13:00:00,11.2,189.015,200.231,185.963,225.736,171.159,171.122,3.47480,229.263,201.867,7962.54
1,2022-07-15 06:00:00,13.9,188.525,200.026,183.010,225.408,170.034,166.027,3.49740,228.926,201.667,8235.40
2,2022-07-14 13:00:00,13.6,189.107,200.470,184.995,225.510,170.889,172.315,3.25573,228.813,202.100,7684.43
3,2022-07-14 06:00:00,11.0,189.208,200.854,183.829,227.578,168.274,167.600,3.34195,230.949,202.448,7940.17
4,2022-07-13 13:00:00,10.7,188.841,200.382,185.034,226.514,168.065,172.359,3.21866,229.778,202.281,7591.85

In [2]:
# Separate the Features (X) from the Target (y)
y = df["N_Butane"]
X = df.drop(["N_Butane", "Date"], axis = 1)

# Split into train data and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=0)

# Import Linear Regression Model

model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make Predictions
y_pred = model.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head()

# Calculated Metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import explained_variance_score as evs

# r2 score
regression_score = r2_score(y_test, y_pred)

# Mean Squared Error (MSE)
from cmath import sqrt
mean_sq_error = mse(y_test, y_pred)
mean_error = sqrt(mean_sq_error).real

# Mean Absolute Error (MAE)
mean_abs_error = mae(y_test, y_pred)

# explained variance score
ev_score = evs(y_test, y_pred)


print(regression_score)
print(mean_error)
print(mean_abs_error)
print(ev_score)

0.116618744197161
15.869854876229006
2.777506401783438
0.11912462082948327