In [1]:
from pathlib import Path
import pandas as pd

In [27]:
data1 = Path('Data/TA_Bad.csv')
TA_df = pd.read_csv(data1)
TA_df.head(20)

,Date,TA.LAB.NC4.VOLPCT,TA.OH.PSIG,TA.RECYCLE.TO.CONTACT.BPD,TA.DP.PSIG
0,5/20/21 13:00,9.4,99.85218048,6885.496582,0.266746789
1,5/20/21 6:00,8.5,102.0362396,6584.85791,0.060048129
2,5/18/21 6:00,7.2,98.51074219,6992.791992,0.006866455
3,5/17/21 13:00,7.7,Error,Error,Error
4,5/17/21 6:00,7.9,100.0030594,6850.363281,0.160209656
5,5/15/21 11:00,8,126.3637314,6985.84668,0.102064125
6,2/14/21 13:00,8.3,Bad,6489.955078,Bad
7,2/14/21 6:00,8.2,Bad,6568.831055,Bad
8,2/13/21 13:00,8.5,Bad,6525.414063,Bad
9,3/26/20 6:00,30.6,-1.467331767,12363.3916,95.05076599
10,3/25/20 13:00,16.1,-1.228884459,11533.52734,94.99382782
11,12/25/19 13:00,13.8,97.16233063,6451.069336,7.169278145
12,12/25/19 6:00,15.4,97.25647736,6517.158203,4.553872108
13,3/27/19 13:53,16.8,97.28072357,6025.606445,5.113654613
14,3/27/19 13:29,16,96.82632446,6032.13916,5.07625103
15,3/27/19 13:28,Error,96.86469269,6005.568359,5.100800037
16,3/27/19 13:21,16,96.94628906,6038.868164,5.11378336
17,12/21/18 15:55,4.3,96.40274048,0,6.154632568
18,12/21/18 15:46,4.3,96.72088623,0,6.198120117
19,12/21/18 15:45,4.3,96.68922424,0,6.172943115

In [28]:
len(TA_df)

20

In [91]:
# Clean TA_df Data 
# Import "other" data source and clean - Weather?
# Import "other" plant data and clean - RX, TB, TC
# Publish clean data sets to SQL
# Pull SQL data to Pandas DF
# Determine variable correlation - chose best variables
# Determine regression model - Linear Regression / Piece Wise Regression
# Train Test Split data
# Note Model Output Performance
# Fine Tune Model
# Use Model to predict "new" datasets - 7/16+
# Create Flask App to share model prediction (really cool if we can upload dataset csv's and the flask app will return predictions)

In [32]:
# Get all column names
columns = list(TA_df.columns)
print(columns)

['Date', 'TA.LAB.NC4.VOLPCT', 'TA.OH.PSIG', 'TA.RECYCLE.TO.CONTACT.BPD', 'TA.DP.PSIG']

In [37]:
# Clean data, drop BAD

TA_df = TA_df[TA_df['TA.LAB.NC4.VOLPCT'].str.contains("Bad")==False]
TA_df = TA_df[TA_df['TA.LAB.NC4.VOLPCT'].str.contains("Error")==False]
TA_df = TA_df[TA_df['TA.OH.PSIG'].str.contains("Bad")==False]
TA_df = TA_df[TA_df['TA.OH.PSIG'].str.contains("Error")==False]
TA_df = TA_df[TA_df['TA.RECYCLE.TO.CONTACT.BPD'].str.contains("Bad")==False]
TA_df = TA_df[TA_df['TA.RECYCLE.TO.CONTACT.BPD'].str.contains("Error")==False]
TA_df = TA_df[TA_df['TA.DP.PSIG'].str.contains("Bad")==False]
TA_df = TA_df[TA_df['TA.DP.PSIG'].str.contains("Error")==False]

TA_df.head(20)

,Date,TA.LAB.NC4.VOLPCT,TA.OH.PSIG,TA.RECYCLE.TO.CONTACT.BPD,TA.DP.PSIG
0,5/20/21 13:00,9.4,99.85218048,6885.496582,0.266746789
1,5/20/21 6:00,8.5,102.0362396,6584.85791,0.060048129
2,5/18/21 6:00,7.2,98.51074219,6992.791992,0.006866455
4,5/17/21 6:00,7.9,100.0030594,6850.363281,0.160209656
5,5/15/21 11:00,8,126.3637314,6985.84668,0.102064125
9,3/26/20 6:00,30.6,-1.467331767,12363.3916,95.05076599
10,3/25/20 13:00,16.1,-1.228884459,11533.52734,94.99382782
11,12/25/19 13:00,13.8,97.16233063,6451.069336,7.169278145
12,12/25/19 6:00,15.4,97.25647736,6517.158203,4.553872108
13,3/27/19 13:53,16.8,97.28072357,6025.606445,5.113654613
14,3/27/19 13:29,16,96.82632446,6032.13916,5.07625103
16,3/27/19 13:21,16,96.94628906,6038.868164,5.11378336
17,12/21/18 15:55,4.3,96.40274048,0,6.154632568
18,12/21/18 15:46,4.3,96.72088623,0,6.198120117
19,12/21/18 15:45,4.3,96.68922424,0,6.172943115

Linear Regression Test

In [96]:
 ## Separate the Features (X) from the Target (y)
y = TA_df["TA.LAB.NC4.VOLPCT"]
X = TA_df.drop(["TA.LAB.NC4.VOLPCT", "Date"], axis = 1)

#print(y)
#print(X)
X.describe()

,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F
count,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589,15589
unique,11582,5670,5781,5854,13826,5685,11114,7279,10656,7828,7916,5770,6656,5150,6719,8706
top,Error,Bad,134.7381592,Bad,-6.900000095,100.033577,Bad Input,Bad,Error,Error,Error,Bad,102.355957,75.08392334,317.0654297,Error
freq,28,457,34,85,586,73,51,313,28,28,28,457,52,66,30,28

In [82]:
## Split into train data and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=0)
X_train.shape

(11691, 16)

In [83]:
# Import Linear Regression Model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [85]:
# Train the model
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Error'