In [5]:
# necessary imports

import pandas as pd
import numpy as np

In [6]:
# loading files and converting into dataframes

file1 = pd.read_csv("Resources/lab_clean-Copy1.csv", index_col=[0])
file2 = pd.read_csv("Resources/ta_pass_02-Copy1.csv", index_col=[0])

lab_data = pd.DataFrame(file1)
ta_clean = pd.DataFrame(file2)

In [7]:
# check if properly loaded
lab_data.head()

            Date  TA.OVH.RECYCLE.NC4.VOLPCT
0  7/15/22 13:00                       11.2
1   7/15/22 6:00                       13.9
2  7/14/22 13:00                       13.6
3   7/14/22 6:00                       11.0
4  7/13/22 13:00                       10.7

In [8]:
# change date column to datetime "Time" column for the purpose of quickly 
# dropping unwanted data by dates later
# as well as an easy merge
lab_data['Time'] = pd.to_datetime(lab_data['Date'])
lab_data = lab_data.drop(columns=['Date'])
lab_data

       TA.OVH.RECYCLE.NC4.VOLPCT                Time
0                           11.2 2022-07-15 13:00:00
1                           13.9 2022-07-15 06:00:00
2                           13.6 2022-07-14 13:00:00
3                           11.0 2022-07-14 06:00:00
4                           10.7 2022-07-13 13:00:00
...                          ...                 ...
15584                       18.0 2013-01-06 06:00:00
15585                       14.4 2013-01-05 13:00:00
15586                       10.2 2013-01-05 06:00:00
15587                        6.1 2013-01-04 13:00:00
15588                        4.9 2013-01-04 06:00:00

[15589 rows x 2 columns]

In [9]:
# checking Tower A data loaded correctly
ta_clean.head()

,Date,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F
0,7/15/2022 13:00,10731.700200,99.301529,134.690353,133.142090,1.432773,100.622315,5919.916992,6399.555664,97.036232,160.828659,177.024338,0.669861,98.631668,74.778496,315.351349,188.916534
1,7/15/2022 6:00,10332.825200,99.471817,134.799347,133.279419,3.479724,99.484406,5935.238281,6395.504883,93.115395,159.833221,175.662384,0.578269,98.897438,72.928696,312.314453,188.058929
2,7/14/2022 13:00,9904.880859,98.972054,134.372711,132.781067,2.860878,99.419403,5968.467773,5933.965332,97.990959,161.156311,178.832550,0.781860,98.191566,73.682632,318.302307,191.867233
3,7/14/2022 6:00,9641.806641,99.947319,134.967651,133.288773,4.899298,99.858498,6020.976074,5902.112793,92.662971,159.716385,176.088470,0.605774,99.337463,74.873863,312.119537,187.954300
4,7/13/2022 13:00,9876.027344,99.606628,135.241089,133.306885,1.202636,100.433968,5917.750488,5749.198730,98.549294,163.994949,182.754105,0.644531,98.956146,76.232300,318.608795,195.616043

In [10]:
# changing date column to Time column in datetime format
ta_clean['Time'] = pd.to_datetime(ta_clean['Date'])

In [11]:
# dropping the now redundant Date column
ta_clean = ta_clean.drop(columns=['Date'])
ta_clean

,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F,Time
0,10731.700200,99.301529,134.690353,133.142090,1.432773,100.622315,5919.916992,6399.555664,97.036232,160.828659,177.024338,0.669861,98.631668,74.778496,315.351349,188.916534,2022-07-15 13:00:00
1,10332.825200,99.471817,134.799347,133.279419,3.479724,99.484406,5935.238281,6395.504883,93.115395,159.833221,175.662384,0.578269,98.897438,72.928696,312.314453,188.058929,2022-07-15 06:00:00
2,9904.880859,98.972054,134.372711,132.781067,2.860878,99.419403,5968.467773,5933.965332,97.990959,161.156311,178.832550,0.781860,98.191566,73.682632,318.302307,191.867233,2022-07-14 13:00:00
3,9641.806641,99.947319,134.967651,133.288773,4.899298,99.858498,6020.976074,5902.112793,92.662971,159.716385,176.088470,0.605774,99.337463,74.873863,312.119537,187.954300,2022-07-14 06:00:00
4,9876.027344,99.606628,135.241089,133.306885,1.202636,100.433968,5917.750488,5749.198730,98.549294,163.994949,182.754105,0.644531,98.956146,76.232300,318.608795,195.616043,2022-07-13 13:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5338,25122.466800,92.152405,127.703857,120.507812,8.922233,94.467171,8196.665039,8761.213867,77.021790,166.543579,186.938477,8.200836,100.465393,102.261360,312.414551,246.087662,2013-01-06 06:00:00
5339,25195.296880,101.445007,133.221436,126.837158,-6.900000,103.817757,8516.427734,9015.898438,89.143372,173.013306,187.103287,8.182526,109.625244,101.425179,314.068603,233.258072,2013-01-05 13:00:00
5340,24632.414060,94.033821,128.207398,121.832275,-6.900000,96.345520,8513.540039,8986.914063,86.091614,167.779556,187.533569,8.205414,102.216339,102.111816,312.402344,242.431641,2013-01-05 06:00:00
5341,24166.078130,95.306396,127.667236,122.308350,-6.900000,97.552490,8439.272461,8972.183594,85.450745,163.192749,187.124634,8.134460,103.534699,102.362060,312.939453,247.558594,2013-01-04 13:00:00
5342,19465.988280,102.985382,131.030273,126.440430,-6.900000,105.233772,8512.096680,9469.200195,85.304260,162.399292,188.204956,8.317566,111.231995,101.971435,312.261963,228.198242,2013-01-04 06:00:00

In [12]:
# merge the dataframes on 'Time' column
lab_ta = ta_clean.merge(lab_data, on='Time')

In [13]:
# check if properly merged
lab_ta

,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F,Time,TA.OVH.RECYCLE.NC4.VOLPCT
0,10731.700200,99.301529,134.690353,133.142090,1.432773,100.622315,5919.916992,6399.555664,97.036232,160.828659,177.024338,0.669861,98.631668,74.778496,315.351349,188.916534,2022-07-15 13:00:00,11.2
1,10332.825200,99.471817,134.799347,133.279419,3.479724,99.484406,5935.238281,6395.504883,93.115395,159.833221,175.662384,0.578269,98.897438,72.928696,312.314453,188.058929,2022-07-15 06:00:00,13.9
2,9904.880859,98.972054,134.372711,132.781067,2.860878,99.419403,5968.467773,5933.965332,97.990959,161.156311,178.832550,0.781860,98.191566,73.682632,318.302307,191.867233,2022-07-14 13:00:00,13.6
3,9641.806641,99.947319,134.967651,133.288773,4.899298,99.858498,6020.976074,5902.112793,92.662971,159.716385,176.088470,0.605774,99.337463,74.873863,312.119537,187.954300,2022-07-14 06:00:00,11.0
4,9876.027344,99.606628,135.241089,133.306885,1.202636,100.433968,5917.750488,5749.198730,98.549294,163.994949,182.754105,0.644531,98.956146,76.232300,318.608795,195.616043,2022-07-13 13:00:00,10.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4432,25122.466800,92.152405,127.703857,120.507812,8.922233,94.467171,8196.665039,8761.213867,77.021790,166.543579,186.938477,8.200836,100.465393,102.261360,312.414551,246.087662,2013-01-06 06:00:00,18.0
4433,25195.296880,101.445007,133.221436,126.837158,-6.900000,103.817757,8516.427734,9015.898438,89.143372,173.013306,187.103287,8.182526,109.625244,101.425179,314.068603,233.258072,2013-01-05 13:00:00,14.4
4434,24632.414060,94.033821,128.207398,121.832275,-6.900000,96.345520,8513.540039,8986.914063,86.091614,167.779556,187.533569,8.205414,102.216339,102.111816,312.402344,242.431641,2013-01-05 06:00:00,10.2
4435,24166.078130,95.306396,127.667236,122.308350,-6.900000,97.552490,8439.272461,8972.183594,85.450745,163.192749,187.124634,8.134460,103.534699,102.362060,312.939453,247.558594,2013-01-04 13:00:00,6.1
4436,19465.988280,102.985382,131.030273,126.440430,-6.900000,105.233772,8512.096680,9469.200195,85.304260,162.399292,188.204956,8.317566,111.231995,101.971435,312.261963,228.198242,2013-01-04 06:00:00,4.9

In [14]:
# needed to easily pull column names for quick reordering
lab_ta.columns

Index(['TA.Charge.BPD', 'TA.OH.PSIG', 'TA.Tray4.F', 'TA.OH.F', 'TA.RECV.PCT',
       'TA.RECV.PSIG', 'TA.REFLUX.BPD', 'TA.RECYCLE.TO.CONTACT.BPD',
       'TA.RECYCLE.TO.CONTACT.F', 'TA.TRAY39.F', 'TA.TRAY45.F', 'TA.DP.PSIG',
       'TA.BTM.PSIG', 'TA.BTM.LEVEL.PCT', 'TA.BTM.REBOIL.OUT.F',
       'TA.TOP.REBOIL.OUT.F', 'Time', 'TA.OVH.RECYCLE.NC4.VOLPCT'],
      dtype='object')

In [15]:
# reording columns so that what will be our target feature is at the end
lab_ta = lab_ta[['Time','TA.Charge.BPD', 'TA.OH.PSIG', 'TA.Tray4.F', 'TA.OH.F', 'TA.RECV.PCT',
       'TA.RECV.PSIG', 'TA.REFLUX.BPD', 'TA.RECYCLE.TO.CONTACT.BPD',
       'TA.RECYCLE.TO.CONTACT.F', 'TA.TRAY39.F', 'TA.TRAY45.F', 'TA.DP.PSIG',
       'TA.BTM.PSIG', 'TA.BTM.LEVEL.PCT', 'TA.BTM.REBOIL.OUT.F',
       'TA.TOP.REBOIL.OUT.F','TA.OVH.RECYCLE.NC4.VOLPCT']]

In [16]:
# checking if reordering worked
lab_ta

,Time,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F,TA.OVH.RECYCLE.NC4.VOLPCT
0,2022-07-15 13:00:00,10731.700200,99.301529,134.690353,133.142090,1.432773,100.622315,5919.916992,6399.555664,97.036232,160.828659,177.024338,0.669861,98.631668,74.778496,315.351349,188.916534,11.2
1,2022-07-15 06:00:00,10332.825200,99.471817,134.799347,133.279419,3.479724,99.484406,5935.238281,6395.504883,93.115395,159.833221,175.662384,0.578269,98.897438,72.928696,312.314453,188.058929,13.9
2,2022-07-14 13:00:00,9904.880859,98.972054,134.372711,132.781067,2.860878,99.419403,5968.467773,5933.965332,97.990959,161.156311,178.832550,0.781860,98.191566,73.682632,318.302307,191.867233,13.6
3,2022-07-14 06:00:00,9641.806641,99.947319,134.967651,133.288773,4.899298,99.858498,6020.976074,5902.112793,92.662971,159.716385,176.088470,0.605774,99.337463,74.873863,312.119537,187.954300,11.0
4,2022-07-13 13:00:00,9876.027344,99.606628,135.241089,133.306885,1.202636,100.433968,5917.750488,5749.198730,98.549294,163.994949,182.754105,0.644531,98.956146,76.232300,318.608795,195.616043,10.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4432,2013-01-06 06:00:00,25122.466800,92.152405,127.703857,120.507812,8.922233,94.467171,8196.665039,8761.213867,77.021790,166.543579,186.938477,8.200836,100.465393,102.261360,312.414551,246.087662,18.0
4433,2013-01-05 13:00:00,25195.296880,101.445007,133.221436,126.837158,-6.900000,103.817757,8516.427734,9015.898438,89.143372,173.013306,187.103287,8.182526,109.625244,101.425179,314.068603,233.258072,14.4
4434,2013-01-05 06:00:00,24632.414060,94.033821,128.207398,121.832275,-6.900000,96.345520,8513.540039,8986.914063,86.091614,167.779556,187.533569,8.205414,102.216339,102.111816,312.402344,242.431641,10.2
4435,2013-01-04 13:00:00,24166.078130,95.306396,127.667236,122.308350,-6.900000,97.552490,8439.272461,8972.183594,85.450745,163.192749,187.124634,8.134460,103.534699,102.362060,312.939453,247.558594,6.1
4436,2013-01-04 06:00:00,19465.988280,102.985382,131.030273,126.440430,-6.900000,105.233772,8512.096680,9469.200195,85.304260,162.399292,188.204956,8.317566,111.231995,101.971435,312.261963,228.198242,4.9

In [17]:
# checking that the data types are floats
lab_ta.dtypes

Time                         datetime64[ns]
TA.Charge.BPD                       float64
TA.OH.PSIG                          float64
TA.Tray4.F                          float64
TA.OH.F                             float64
TA.RECV.PCT                         float64
TA.RECV.PSIG                        float64
TA.REFLUX.BPD                       float64
TA.RECYCLE.TO.CONTACT.BPD           float64
TA.RECYCLE.TO.CONTACT.F             float64
TA.TRAY39.F                         float64
TA.TRAY45.F                         float64
TA.DP.PSIG                          float64
TA.BTM.PSIG                         float64
TA.BTM.LEVEL.PCT                    float64
TA.BTM.REBOIL.OUT.F                 float64
TA.TOP.REBOIL.OUT.F                 float64
TA.OVH.RECYCLE.NC4.VOLPCT           float64
dtype: object

In [18]:
# summary statistics of merged dataframe
lab_ta.describe()

,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F,TA.OVH.RECYCLE.NC4.VOLPCT
count,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000,4437.000000
mean,15620.672366,97.723350,134.151958,131.517451,9.289621,100.181026,6990.922152,6726.168323,84.443208,164.227243,178.430697,7.281588,103.294407,90.838389,309.610095,210.533238,11.012110
std,4263.920510,6.221024,3.588488,4.004188,8.999482,4.536183,1307.468604,989.504336,8.752999,6.896627,10.471157,9.092164,10.358475,12.975426,12.238055,17.862308,15.567706
min,0.000000,-1.532560,102.691650,102.038574,-6.900000,57.708740,-836.645019,0.000000,27.513123,131.103516,136.929321,0.002177,3.174019,0.000000,185.351562,150.372314,0.000000
25%,12188.400390,96.929169,132.424927,129.528809,6.722509,99.589539,6349.304199,6297.396973,79.360962,160.906067,174.343872,5.145360,99.867859,82.113541,301.684570,197.738648,8.200000
50%,15695.221680,97.400665,133.936645,131.686401,9.929183,100.012207,7142.279297,6497.564453,85.130310,164.300552,177.410904,7.573708,104.711151,87.947777,310.418701,207.238769,10.200000
75%,17976.638670,99.451538,135.272217,133.261917,13.606541,100.360107,7897.381836,6776.832031,89.758301,167.590332,181.064835,8.386230,106.027229,102.352913,319.512940,219.818130,12.500000
max,29810.134770,133.076477,194.899170,194.660858,105.000000,136.087036,12522.957030,16473.312500,113.681038,299.072266,331.774933,101.661385,141.533661,199.996948,359.384460,329.602081,1005.000000

In [19]:
# export cleaned data as ta_pass_03.csv
#lab_ta.to_csv("Resources/ta_pass_03.csv")

In [52]:
# outlier identification function

def find_outliers(df):
    q1 = df.quantile(0.25)
    q3 = df.quantile(.75)
    iqr = q3-q1
    lower_lim = q1 - (1.5 * iqr)
    upper_lim = q3 + (1.5 * iqr)
    outliers = df[((df<lower_lim) | (df>upper_lim))]
    return outliers

In [56]:
# making a separate df to hold outlier information
test_df = lab_ta.drop(columns=['Time'])

outliers = find_outliers(test_df)
outliers

,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F,TA.OVH.RECYCLE.NC4.VOLPCT
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4432,NaN,92.152405,127.703857,120.507812,NaN,94.467171,NaN,8761.213867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4433,NaN,NaN,NaN,NaN,-6.9,103.817757,NaN,9015.898438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4434,NaN,NaN,NaN,121.832275,-6.9,96.345520,NaN,8986.914063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4435,NaN,NaN,127.667236,122.308350,-6.9,97.552490,NaN,8972.183594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4436,NaN,NaN,NaN,NaN,-6.9,105.233772,NaN,9469.200195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
# summary statistics on outliers
outliers.describe()

,TA.Charge.BPD,TA.OH.PSIG,TA.Tray4.F,TA.OH.F,TA.RECV.PCT,TA.RECV.PSIG,TA.REFLUX.BPD,TA.RECYCLE.TO.CONTACT.BPD,TA.RECYCLE.TO.CONTACT.F,TA.TRAY39.F,TA.TRAY45.F,TA.DP.PSIG,TA.BTM.PSIG,TA.BTM.LEVEL.PCT,TA.BTM.REBOIL.OUT.F,TA.TOP.REBOIL.OUT.F,TA.OVH.RECYCLE.NC4.VOLPCT
count,41.000000,949.000000,336.000000,287.000000,664.000000,1538.000000,172.000000,814.000000,110.000000,98.000000,179.000000,640.000000,255.000000,57.000000,33.000000,113.000000,192.000000
mean,17700.180372,96.437474,139.470569,133.392917,-0.983747,100.473771,4308.519581,7986.333103,75.129156,167.134357,199.131215,7.765768,100.460613,72.849561,291.339584,265.788779,25.132292
std,13488.224614,12.995649,8.961749,11.773135,16.962280,7.677170,3383.735933,1752.429110,22.847436,33.601482,40.523119,23.372405,40.439689,61.702114,47.614630,19.879302,72.137105
min,0.000000,-1.532560,102.691650,102.038574,-6.900000,57.708740,-836.645019,0.000000,27.513123,131.103516,136.929321,0.002177,3.174019,0.000000,185.351562,150.372314,0.000000
25%,43.794273,92.136383,139.623451,122.892765,-6.900000,95.019531,2154.883484,7818.320435,60.141754,147.679901,163.665772,0.105706,115.336994,21.635437,270.324707,256.854248,19.200001
50%,26958.464840,92.500305,141.502380,139.385986,-6.900000,97.713470,3206.244751,8201.000977,62.731173,150.042725,192.953812,0.182871,117.974853,39.322662,272.357178,259.381103,21.400000
75%,27801.376950,105.022430,143.533325,141.192627,-6.900000,104.817200,3903.295838,8594.729981,105.738394,179.959106,201.828011,0.247383,122.032932,142.654419,348.138428,268.194580,25.500000
max,29810.134770,133.076477,194.899170,194.660858,105.000000,136.087036,12522.957030,16473.312500,113.681038,299.072266,331.774933,101.661385,141.533661,199.996948,359.384460,329.602081,1005.000000

- may want to cap the outliers, decide what needs to be dropped, and what can be kept
- first need to run some tests to see feature importances, so that I can avoid getting rid of whole rows when I can get rid of unimportant features (that may contain many of the outliers) instead